### ISSUE TITLE
 instance.isDisabled is not a function at Controller.<anonymous>

### ISSUE THREAD

**Issue by argmhz** [totaljs/flowcomponents#14]
Hi, 
it looks like you broke the Http route in the commit or do i  miss something in the making of a http route ? 

https://github.com/totaljs/flowcomponents/commit/72fcf7ba07a79d34400b0ece312b6e7ef1406cd0

```
instance.isDisabled is not a function (http://localhost:8000/api/noget) TypeError: instance.isDisabled is not a function at Controller.<anonymous> (/home/app/flow/httproute.js:184:36)

``` 
nice work by the way :+1:

**Comment by molda** [comment]
Hi, the isDisabled method has been added recently. Just update the flow package.

**Comment by argmhz** [comment]
Thanks :+1:
