### ISSUE TITLE
AlexaRouter Component Missing URL Path

### ISSUE THREAD

**Issue by kevalkothari** [totaljs/flowcomponents#16]
URL Path shown in demo video but it seems it is missing in AlexaRoute component 
![alexaurlpath](https://user-images.githubusercontent.com/1439447/41048241-f1c07068-69cb-11e8-811a-9492dcf66d80.png)

**Comment by molda** [comment]
Hi, I recommended John who created the component to use it with httproute component so he removed the url but haven't updated the video. So you need to use httproute and connect it to alexarouter.
