### ISSUE TITLE
Support for HTTP HEAD method

### ISSUE THREAD

**Issue by David-Melo** [totaljs/flowcomponents#19]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD

I was attempting to setup a Trello webhook with the HTTP Route component. Trello sends a HEAD request to the url before it can allow you to create a webhook. The current HTTP endpoints don't have HEAD as one of the request methods.

I was able to copy and paste the HTTP Route component into a new one and just add HEAD as one of the dropdown options and was able to get the Trello webhook running.

Is there any reason this method is not supported? Or is it just not that commonly used?

Thanks, great framework. Having lots of fun using it.

**Comment by petersirka** [comment]
Hi @David-Melo,
Total.js framework processes `head` method automatically according to the registered routes. So it must work without any problem. 

__If you have a problem ...__
Can you capture head request headers and can you show me the settings of your HTTP Route?

Thank you!
