### ISSUE TITLE
Already buy premium account, how to auto install latest flow components

### ISSUE THREAD

**Issue by backendbox** [totaljs/flowcomponents#2]
Try to auto install flow components but some of theme is not up to date. How to install all of them ? latest !

**Comment by petersirka** [comment]
I prepare a new version (max. 2-3 weeks) and the new version will be linked with GitHub `flowcomponents` repository __directly__.

__How to solve the current state?__
- open __Flow components__ database in your Flow
- then add URL to Flow component e.g. <https://raw.githubusercontent.com/totaljs/flowcomponents/master/counter/counter.js> and press enter (component will be updated)
