### ISSUE TITLE
Issues with multiple outputs in Function component

### ISSUE THREAD

**Issue by khaledkhalil94** [totaljs/flowcomponents#20]
Hello,

I've noticed couple issues with the Function component when you choose multiple outputs.

Tested on a fresh install of Flow v5.1

1- All output connection links are visually removed once you change the output number.
2- If you don't specify an index in the `send` function, the component sends data to the first output rather than all outputs.

Thanks.

**Comment by petersirka** [comment]
Hi @khaledkhalil94,
1. yes <https://github.com/totaljs/flowcomponents/blob/master/function/function.js#L54> because there is a problem with comparision. But yes, we can improve it...
2. this depends on the data, which type of data are you sending?

**Comment by khaledkhalil94** [comment]
String

**Comment by petersirka** [comment]
Sorry for delay. I'm not author of this component, but I'll fix it today/tomorrow later. I have contacted author but unfortunately the author doesn't have any time for it.

I'll give you feedback.

**Comment by petersirka** [comment]
I have fixed it. I'll think about:

> All output connection links are visually removed once you change the output number.

Because it's a bit complicated to compare outputs but I'll add a support for it into the Flow core.

**Comment by khaledkhalil94** [comment]
Hello, just wondering if there has been any updates to the links issue ?

**Comment by petersirka** [comment]
Hi @khaledkhalil94, it's fixed. Please download the Flow from <https://github.com/totaljs/flow> and let me know. BTW: you need to update all components.
