### ISSUE TITLE
HTTP route component returns 404 Not Found for all methods except GET

### ISSUE THREAD

**Issue by khaledkhalil94** [totaljs/flowcomponents#28]
Hello,

I've been trying to use the HTTP Route component but I faced an issue which is that the route returns 404 Not Found if I use any method other than `GET`.

**Comment by petersirka** [comment]
Please create a demo Flow and export it. I need to test it.

**Comment by khaledkhalil94** [comment]
[flow_20190617-1107.txt](https://github.com/totaljs/flowcomponents/files/3295601/flow_20190617-1107.txt)

**Comment by petersirka** [comment]
It works:

![image](https://user-images.githubusercontent.com/2414252/59585394-a6619d80-90e0-11e9-803d-f43bbcf628f8.png)

**Comment by molda** [comment]
I also just tested latest versions (Flow and HTTP Route) from github and it all (GET,POST,PUT,DELETE) works just fine.

**Comment by khaledkhalil94** [comment]
Turns out I was sending `application/javascript` in `Content-Type` instead of `application/json` and for some  reasons it was returning 404.

Maybe it should return 400 in this case, what do you think ?

Thanks anyway for the fast reply guys, I appreciate it :)

**Comment by petersirka** [comment]
`application/javascript`???? __How can the server parse it?__ What will be the parsed object?

- `404` I must check which rules are needed for `404`, but for similar cases the server responds with 400 status code
