### ISSUE TITLE
How to display data on jcomponent?

### ISSUE THREAD

**Issue by DPain** [totaljs/flowcomponents#29]
Hi, I'm trying to create a display result component that receives data from its previous block and display the data on the textboxes that are within the component's settings window when I open it.

My approach is that I would modify the exports.options value during the instance.on('data') event and then add a client side ON('open.componentname') event to modify the textbox according to the exports.options value, but I noticed that the exports.options value that is modified from the server side does not get reflected on the client side.

Is my approach incorrect and is there any other way to display received data on the settings form?

Thanks!

**Comment by molda** [comment]
You need to call `instance.reconfig()` to update options on client.

**Comment by DPain** [comment]
Ah thanks! I got it to work!
