### ISSUE TITLE
How to use component http request ?

### ISSUE THREAD

**Issue by backendbox** [totaljs/flowcomponents#3]
I can set url, http method, serialization, headers, cookie ... but can't set post data. Can you help me ?

**Comment by petersirka** [comment]
Hi @backendbox,
request data are data on the input. 

So you have to send data to HTTP Requet and HTTP Request sends these data via HTTP protocol.

**Comment by backendbox** [comment]
@petersirka Thank you so much !
Now i know how to work with it !
