### ISSUE TITLE
How to use data scopes in component?

### ISSUE THREAD

**Issue by DPain** [totaljs/flowcomponents#30]
Hi, I'm trying to use anonymous data scopes on a component and was wondering how I could use this in multiple types of components.

The problem I am experiencing is that the scope init function would only get executed once during initialization. When using scopes in two different components, whenever opening the settings page of a component, the page will no longer use the correct scope because the scope is set only in the init function. Using two of the same type of components will work fine, but any other components together will cause the issue.

**Comment by petersirka** [comment]
Hi. Can you send me some example?

**Comment by DPain** [comment]
Thank you, I have sent you an example via email.

**Comment by DPain** [comment]
Thanks for the help. It works perfectly well!
I should've looked at the index.html and noticed that each components has each of their own scope.
