### ISSUE TITLE
HTTP Request component with FiFo + dynamic url

### ISSUE THREAD

**Issue by snu-ceyda** [totaljs/flowcomponents#32]
I'm trying to send a bunch of requests to different urls in a for loop;
as per documentation I do; "set('key', i);" in a for loop in the repository node and set the http node url accordingly like below, everything works as expected:
![image](https://user-images.githubusercontent.com/15624271/74712230-268c6400-5269-11ea-97d9-7e269fabb5a6.png)

**But** when I try to queue those requests in a fifo pipeline like below; 
where code component does send(0,url) in a for loop and the repository node just set('key', value)
![image](https://user-images.githubusercontent.com/15624271/74712618-0f01ab00-526a-11ea-9b3f-0c834e2b105e.png)
The fifo pipeline just stops because the fo component loses the proper reference to the fi component.(I think the html request component overrides it...maybe)

+I have tried a bunch of different combinations but repository+fifo  just doesn't work as I want. I think being able to set the dynamic url in some other way (not in repository) might solve this but im not familiar enough with totaljs/flow. I think it would also be nice to be able to set the whole url dynamically ( http://{key} ), not just partially ( http://etc.etc/{key} )

Is there a better way to send dynamic request through a fifo queue?

**Comment by petersirka** [comment]
Can you create some Flow and export it here? I'll try it.

**Comment by snu-ceyda** [comment]
You can test it with this flow

[http_test_flow.txt](https://github.com/totaljs/flowcomponents/files/4223932/http_test_flow.txt)

BTW I have versions
Node.js       : v13.8.0
Total.js      : v3.3.0
Total.js Flow  : 1.0.0
and the latest updates on the components

**Comment by petersirka** [comment]
Hi, sorry for delay - I forgot on you. I found a bug in `FI` component, I have updated it and now it works correcly.

**Comment by snu-ceyda** [comment]
I have updated and tested it 
with this fix "fi+repository+fo" works .
but unfortunately "fi+http request+fo"  still doesn't work, the queue gets stuck (the second flow in the example code)
![image](https://user-images.githubusercontent.com/15624271/75129857-8de56080-570e-11ea-93ad-f2d98881a231.png)

I think this has to do with "http request" component overriding the repository and losing the reference to the fi component
![image](https://user-images.githubusercontent.com/15624271/75129842-7d34ea80-570e-11ea-8d90-221c7f65d9ff.png)

**Comment by petersirka** [comment]
It works for me. Try it: [flow.zip](https://github.com/totaljs/flowcomponents/files/4257243/flow.zip)

- import `flow.txt`
- run service `$ node service.js`

**Comment by snu-ceyda** [comment]
Sorry I can confirm it works now!
had to do a fresh install, something must have gotten messed up before
Thanks
