### ISSUE TITLE
Hello, Can you tell me how to use mqtt on flow ?

### ISSUE THREAD

**Issue by backendbox** [totaljs/flowcomponents#4]
Thanks

**Comment by molda** [comment]
Hi @backendbox first you need to add MQTT Broker component and setup the connection to a server.
Once you save the settings and the component's status is `connected` add a MQTT publish or subscribe component and in the setting form select the broker You just created and fill in the other required field like topic etc. 
Now you should be ready to publish/subcribe.

Hope it helps. Let me know if you run into any problem, i'll be happy to help.

Thanks.

**Comment by backendbox** [comment]
Can i use mosca to create server (mqttserver component) ?

**Comment by molda** [comment]
Well I would only recommended it for testing purposes. For production there are better options like Mosquitto or some cloud providers.

Also you can improve the mqttserver component yourself to make it more useful :)

**Comment by backendbox** [comment]
I see ! Thank you so much !
