### ISSUE TITLE
Update Components 

### ISSUE THREAD

**Issue by badlee** [totaljs/flowcomponents#43]
Hi, Some flow components not work with Total.js 4, like httproute.
Please Update.

**Comment by petersirka** [comment]
Hi @badlee.
Yes, we know it. Temporarily: I recommend to use Total.js v3 for Flow due to 100% backward compatibility. Not all components are compatible with Total.js 4 yet. We will work on it in short time.

**Comment by badlee** [comment]
I testing and update some component in my effort to learn Total.js.

**Comment by petersirka** [comment]
@badlee thank you so much!
