### ISSUE TITLE
Flow Nosql Query

### ISSUE THREAD

**Issue by backendbox** [totaljs/flowcomponents#5]
Can i query nosql on flow like : LIKE, = ... ?

**Comment by molda** [comment]
Hi @backendbox  you can use 
- builder.filter
but instead of function use regexp

```javascript
[
    ['filter', 'prop-name', /^hello/]
]
```

The above is similar to `LIKE hello%`

**Comment by backendbox** [comment]
Relly nice @molda Thankyou !

**Comment by backendbox** [comment]
Sorry, Can you help me do it on Flow. I still can't get it !

**Comment by molda** [comment]
I'm sorry i was looking into source code of SchemaBuilder.filter instead of DatabaseBuilder.filter.
So filter is not supported, currently you can do something like shown bellow in function component:

```
send([['filter', function(doc){
	return doc.firstname.startsWith('P');
}]]);
```

**Comment by backendbox** [comment]
Just try : 
send([
 ['limit', 2]
]);
It's working, but : 
send([
 ['where', 'updated_id', flowdata.data.params.updated_id],
 ['limit', 2]
]);
is not working !
Can you help me fix it ?

P/s : After nosql function error, the server will stuck and any query later will timeout error !

**Comment by molda** [comment]
I can't seem to reproduce this. It's working for me as expected.
Can you be more specific about *"After nosql function error,..."*? What is the error?

**Comment by backendbox** [comment]
@molda 
It's work !

About the error, for example : if i made a bad function and send a request, the server will show error and any later request will timeout !
try this code : 
send(
[
['search','message',"123"]
]
);

Another question please : can i query Where with child elements, for example : 
{
 "message" : {
"id": 123
}
}
How can i query where id = 123 ?

**Comment by molda** [comment]
I'll look at the error later today.
To answer your *Another question*:
You can use `filter` as I mentioned above.
`where` does not support nested objects.

**Comment by backendbox** [comment]
Ok, Thank you so much @molda

**Comment by backendbox** [comment]
<img width="607" alt="screen shot 2017-05-25 at 6 14 01 pm" src="https://cloud.githubusercontent.com/assets/14541106/26448142/fe3f0a72-4175-11e7-8114-ebb80c1612a3.png">
This is what i got when try this code : 
`send([['filter', function(doc){
	return doc.firstname.startsWith('P');
}]]);`

**Comment by molda** [comment]
@backendbox This `doc.firstname.startsWith('P');` is just an example, if your document does not have a `firstname` property you get an error.

Example to show what you have asked for above *"How can i query where id = 123 ?"* in nested objects:

```
send([['filter', function(doc){
	return doc && doc.message && doc.message.id === 123;
}]]);
```
