### ISSUE TITLE
Component Code: apply button almost out of screen

### ISSUE THREAD

**Issue by h2atecnologia** [totaljs/flowcomponents#57]
Suggestion - I guess 400 to codemirror,  would be a good value, instead 500.

**Comment by molda** [comment]
Well this is relative to the screen resolution. To be honest i would prefer even more than 500px.
The size is ok for 1920x1080 which i believe is the standard these days.
What screen resolution do you have?

**Comment by h2atecnologia** [comment]
I have a 1920x1080 screen (macos). 
Sharing my screen.
Note that to click the button it is necessary to scroll the screen.

![Screen Shot 2022-03-18 at 12 55 29](https://user-images.githubusercontent.com/5349888/159038030-f5c0eee0-d3ac-4f80-9cb6-43a5720c3f8e.png)

**Comment by h2atecnologia** [comment]
But, you have reason. this is relative. And sure how much more space to code, it better.
