### ISSUE TITLE
Flowboard components icons is wrong

### ISSUE THREAD

**Issue by h2atecnologia** [totaljs/flowcomponents#58]
flowboardlight
fa-lightbulb-o => lightbulb-o

flowboardoutput
fa-commenting => commenting-o

flowboardsocket
fa-plug => plug

**Comment by molda** [comment]
Thanks a lot.

Also you may want to consider using the latest version of Flow v10 which is quite different with many improvements.
https://blog.totaljs.com/posts/1066362001wn71b/

**Comment by h2atecnologia** [comment]
About icons: I guess the CDN takes some time to be updated... 

About v10:  I fully understand that this is a WIP. It makes perfect sense. 

Unfortunately I have a new project to code urgently. Maybe I need an AMQP broker. I already tried to create a component for this (need to fix resubscribe). This project will run on AWS. Maybe in containers and/or Ec2/arm. More than a Flow instance and with the local design, but with the deployment of the design.json file.
Many more others components deverão ser codificados (S3, Lambda, SQS, SNS, etc).
I will share with you and sure: I will need some help.
