### ISSUE TITLE
Flow rest CORS component: allow more settings

### ISSUE THREAD

**Issue by h2atecnologia** [totaljs/flowcomponents#59]
This is some enhancement. Not a bug.

Allow: 
- origin option (with regex - maybe dynamic too)
- maxAge option
- allowedHeaders option
- preflightContinue option (depends on http code)

Some questions:
- is it possible to have more than one CORS (1 per route) ?
- one CORS settings per route, overrides a gobal CORS ?

**Comment by molda** [comment]
We are not planning on adding new features to Flow v6 or its components, we will only fix bugs if there are any. We are currently focusing on the new release of Flow v10.
Feel free to update the component yourself and send us a Pull Request if you feel like it.

**Comment by h2atecnologia** [comment]
OK.  I will try to implement this.  tks.

BTW.  I updated the text from issue before your answer.

**Comment by molda** [comment]
It is possible to set CORS per route.
See the documentation https://docs.totaljs.com/total4/407ff001jy51c/#4894d001fw51c
The restcors component does not support all the options the CORS method supports. So there's a room for improvement.

**Comment by h2atecnologia** [comment]
I gonna work.
;-)
